### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ehsanmok** [jmhessel/fmpytorch#1]
Hi

After running `python setup.py install` and using FactorizationMachine layer in a simple example, I got `ModuleNotFoundError: No module names 'second_order_fast'` in `from second_order_fast import SecondOrderInteraction` continuing with `'second_order_naive'` ModuleNotFoundError!

I'm on Ubuntu 14.04, Anaconda4.4.0, python=3.6 and Cython=0.26 (gcc 4.8.4).

**Comment by jmhessel** [comment]
Thanks for the issue report -- I'll check it out shortly!

**Comment by ehsanmok** [comment]
Apparently `find_packages()` or `['fmpytorch', 'fmpytorch.second_order']` ignores `second_order_fast_inner`.

**Comment by jmhessel** [comment]
Alright, I think I fixed it -- python 3 import syntax from the same directory is different. If it's not working, feel free to re-open the issue!

Thanks for testing out python 3!
